name: CMake on macOS

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: check cmake
        shell: bash
        run: cmake --version

      - name: cache catch2
        id: cache-catch
        if: ${{ !env.ACT }}
        uses: actions/cache@v4
        with:
          path: ./Catch2
          key: ${{matrix.os}}-Catch2-${{matrix.build_type}}-
          restore-keys: ${{matrix.os}}-Catch2-${{matrix.build_type}}-

      - name: build catch2
        if: steps.cache-catch.outputs.cache-hit != 'true' && !env.ACT
        shell: bash
        run: |
          git clone https://github.com/catchorg/Catch2.git --depth 1
          cd Catch2
          cmake -B build -D BUILD_TESTING=OFF
          sudo cmake --build build/ --target install
          cd ..

      - name: install catch2
        if: ${{ !env.ACT }}
        shell: bash
        run: |
          cd Catch2
          sudo cmake --build build/ --target install
          cd ..

      - name: Configure CMake
        shell: bash
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@15)/bin/clang++
      - name: Build
        shell: bash
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure

