name: CMake on Windows

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: build catch2
        shell: powershell
        run: |
          git clone https://github.com/catchorg/Catch2.git --depth 1
          cd Catch2
          md build
          cmake -B build -D BUILD_TESTING=OFF
          cmake --build build/ --target install --config ${{matrix.build_type}}
          cd ..

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure

