name: CMake on Windows

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
        build_type: [Release]
        compiler: [mingw]


    steps:
      - uses: actions/checkout@v4

      - name: cache catch2
        id: cache-catch
        uses: actions/cache@v4
        with:
          path: ./Catch2
          key: ${{matrix.os}}-Catch2-
          restore-keys: ${{matrix.os}}-Catch2-

      - name: build catch2
        if: steps.cache-catch.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          git clone https://github.com/catchorg/Catch2.git --depth 1
          cd Catch2
          cmake -B build -H . -D BUILD_TESTING=OFF
          cmake --build build/ --target install
          cd ..

      - name: install catch2
        shell: powershell
        run: |
          cd Catch2
          cmake --build build/ --target install
          cd ..

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure
